name: "go-demo"
mode: "pro"
port: 8090
version: "v0.0.1"

mysql:
  host: 127.0.0.1
  port: 3306
  user: "root"
  password: "123456"
  dbname: "go-demo"
  max_open_conns: 10
  max_idle_conns: 5

redis:
  host: 127.0.0.1
  port: 6379
  password: ""
  db: 0
  pool_size: 10
